import {Open_Sans } from "next/font/google";
import "./globals.css";
import Footer from "@/components/global/Footer";
import ScrollContext from "@/services/ScrollContext";
import Navbar from "@/components/global/Navbar";
import { Providers } from "@/lib/Providers";
import RouteChangeCloser from "@/services/RouteChangeCloser";
import ServiceInitializer from "@/services/ServiceInitializer";

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
  display: "swap",
//   weight: ["400", "500", "600", "700"], 
});

// const geistMono = Geist_Mono({
// 	variable: "--font-geist-mono",
// 	subsets: ["latin"],
// });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={`${openSans.variable} antialiased `}>
				{/* <ScrollContext> */}
					<Providers>
						<ServiceInitializer />
						<Navbar />
						{children}
						<Footer />
						<RouteChangeCloser />
					</Providers>
				{/* </ScrollContext> */}
			</body>
		</html>
	);
}
